name: Build and Release an Executable of the Wordle Assistant

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            output_name: WordleAssistant-linux
            separator: ":"
          - os: windows-latest
            output_name: WordleAssistant-windows
            separator: ";"
          - os: macos-latest
            output_name: WordleAssistant-macos
            separator: ":"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller colorama

      # Build the one-file executable and include the word list file
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --console --name WordleAssistant --add-data "wordlewords.txt${{ matrix.separator }}." wordle_assistant.py

      # Move and rename binaries, make Linux executable
      - name: Prepare binary for artifact
        shell: bash
        run: |
          mkdir -p release
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            mv dist/WordleAssistant release/WordleAssistant-linux.run
            chmod +x release/WordleAssistant-linux.run
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv dist/WordleAssistant.exe release/WordleAssistant-windows.exe
          else
            mv dist/WordleAssistant release/WordleAssistant-macos
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output_name }}
          path: release/*