name: Build and Release an Executable of the Wordle Assistant

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            extension: ""
            output_name: WordleAssistant-linux
            separator: ":"
          - os: windows-latest
            extension: ".exe"
            output_name: WordleAssistant-windows
            separator: ";"
          - os: macos-latest
            extension: ""
            output_name: WordleAssistant-macos
            separator: ":"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller colorama

      # Build the one-file executable and include the word list file
      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --console --name WordleAssistant --add-data "wordlewords.txt${{ matrix.separator }}." wordle_assistant.py

      - name: Make Linux binary executable
          if: matrix.os == 'ubuntu-latest'
          run: chmod +x release/WordleAssistant-linux

      # Move the build output to a standard folder with a clear name
      - name: Rename executable
        shell: bash
        run: |
          mkdir -p release
          mv dist/WordleAssistant${{ matrix.extension }} release/${{ matrix.output_name }}${{ matrix.extension }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output_name }}
          path: release/*