name: Build and Release Cross-Platform Binaries for the Wordle Assistant

permissions: 
  contents: write

on:
  push:
    tags:
      - 'v*'  # Triggers when you push a tag like v1.0.0
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            output_name: WordleAssistant.exe
            asset_name: WordleAssistant-Windows.exe
            separator: ";"
          - os: macos-latest
            output_name: WordleAssistant
            asset_name: WordleAssistant-macOS
            separator: ":"
          - os: ubuntu-20.04  # Use older Ubuntu for better compatibility
            output_name: WordleAssistant
            asset_name: WordleAssistant-Linux.tar.gz
            separator: ":"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller colorama
    
    - name: Build executable
      run: |
        pyinstaller --onefile --add-data "wordlewords.txt${{ matrix.separator }}." --name WordleAssistant wordle_assistant.py
    
    - name: Package for Linux
      if: runner.os == 'Linux'
      run: |
        # Create package directory
        mkdir -p wordle-assistant-linux
        cp dist/WordleAssistant wordle-assistant-linux/
        
        # Create launcher script
        cat > wordle-assistant-linux/run.sh << 'EOF'
        #!/bin/bash
        cd "$(dirname "$0")"
        ./WordleAssistant
        read -n 1 -s -r -p "Press any key to close..."
        EOF
        
        chmod +x wordle-assistant-linux/run.sh
        chmod +x wordle-assistant-linux/WordleAssistant
        
        # Create README
        cat > wordle-assistant-linux/README.txt << 'EOF'
        Wordle Assistant for Linux
        ===========================
        
        To play:
        1. Double-click "run.sh"
           OR
        2. Open terminal and run: ./run.sh
        
        If double-click doesn't work:
        1. Right-click run.sh → Properties → Permissions
        2. Check "Allow executing file as program"
        3. Try again
        
        Enjoy!
        EOF
        
        # Package it
        tar -czf WordleAssistant-Linux.tar.gz wordle-assistant-linux/
        mv WordleAssistant-Linux.tar.gz dist/
    
    - name: Rename output (macOS)
      if: runner.os == 'macOS'
      run: |
        chmod +x dist/${{ matrix.output_name }}
        mv dist/${{ matrix.output_name }} dist/${{ matrix.asset_name }}
    
    - name: Rename output (Windows)
      if: runner.os == 'Windows'
      run: |
        move dist\${{ matrix.output_name }} dist\${{ matrix.asset_name }}
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.asset_name }}
        path: dist/${{ matrix.asset_name }}
    
    - name: Upload to Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/${{ matrix.asset_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}