name: Build and Release Cross-Platform Binaries for the Wordle Assistant

permissions: 
  contents: write

on:
  push:
    tags:
      - "v*"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install colorama pyinstaller
      - run: pyinstaller --onefile --name "Wordle Assistant" --console --add-data "wordlewords.txt;." wordle_assistant.py
      - name: Upload Windows executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/Wordle Assistant.exe
          asset_name: "Wordle Assistant Windows.exe"
          asset_content_type: application/octet-stream

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install colorama pyinstaller
      - run: pyinstaller --onefile --name "Wordle Assistant" --console --add-data "wordlewords.txt:." wordle_assistant.py
      - name: Upload macOS executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/Wordle Assistant
          asset_name: "Wordle Assistant macOS.app.zip"
          asset_content_type: application/zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - run: pip install colorama pyinstaller
      - run: pyinstaller --onefile --name "Wordle Assistant" --console --add-data "wordlewords.txt:." wordle_assistant.py
      - name: Upload Linux executable
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/Wordle Assistant
          asset_name: "Wordle Assistant Linux"
          asset_content_type: application/octet-stream